# Generated by Django 3.1.4 on 2020-12-07 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Csv_File_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('Industry_aggregation_NZSIOC', models.CharField(max_length=30)),
                ('Industry_code_NZSIOC', models.CharField(max_length=30)),
                ('Industry_name_NZSIOC', models.CharField(max_length=80)),
            ],
        ),
    ]
